# See config.example.yml for documentation.
object_base: orig/SQME52
object: sys/main.dol
hash: 7b8f717786e2f1dceb1a277aa027dba0c14cfd4a
symbols: config/SQME52/symbols.txt
splits: config/SQME52/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
ldscript_template: assets/ldscript.lcf
mw_comment_version: 14