# See config.example.yml for documentation.
object_base: orig/SPDE52
object: sys/main.dol
hash: b2df499fc3325ad5a11db613f62256888be9ead8
symbols: config/SPDE52/symbols.txt
splits: config/SPDE52/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
ldscript_template: assets/ldscript.lcf
mw_comment_version: 14