# See config.example.yml for documentation.
object_base: orig/SPDE52
object: sys/main.dol
hash: 0123456789abcdef0123456789abcdef01234567
symbols: config/SPDE52/symbols.txt
splits: config/SPDE52/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11